# Generated by Django 5.1 on 2025-11-06 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('tipo', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=50)),
                ('piso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_reserva', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(max_length=50)),
                ('huesped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Hotel.huesped')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_checkin', models.DateField()),
                ('fecha_checkout', models.DateField()),
                ('estatus', models.CharField(max_length=50)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Hotel.habitacion')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Hotel.reserva')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='habitaciones',
            field=models.ManyToManyField(through='app_Hotel.ReservaHabitacion', to='app_Hotel.habitacion'),
        ),
    ]
