# Generated by Django 5.1 on 2025-11-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='huesped',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='habitaciones',
        ),
        migrations.RemoveField(
            model_name='reservahabitacion',
            name='reserva',
        ),
        migrations.RemoveField(
            model_name='reservahabitacion',
            name='habitacion',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='piso',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='capacidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='ocupada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='ubicacion',
            field=models.CharField(default='Sin asignar', max_length=100),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='numero',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(choices=[('Sencilla', 'Sencilla'), ('Doble', 'Doble'), ('Suite', 'Suite')], default='Sencilla', max_length=50),
        ),
        migrations.DeleteModel(
            name='Huesped',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
        migrations.DeleteModel(
            name='ReservaHabitacion',
        ),
    ]
